name: 'Lubycon Github Reviewer Slack Notify'
description: '루비콘 허브 내에서 사용되는 깃허브 PR 리뷰 노티피케이션 액션입니다'
branding:
  color: blue
  icon: at-sign
inputs:
  base-branch:
    description: "Branch that you will be opening PRs in to (e.g. 'staging', 'master')."
    required: true
  slack-bot-token:
    description: "OAuth token for your Slack App Bot to sign requests to Slack's API with."
    required: true
  channel-id:
    description: 'ID of the channel or conversation in Slack you would like messages posted to.'
    required: true
  github-token:
    description: 'Personal access token with repository rights.'
    required: true
  my-slack-user-id:
    description: 'Your slack user id in Lubycon Hub workspace.'
runs:
  using: 'node12'
  main: 'dist/index.js'
