name: 'Lubycon Github Reviewer Notify'
description: '루비콘 허브 내에서 사용되는 깃허브 PR 리뷰 노티피케이션 액션입니다'
branding:
  color: blue
  icon: at-sign
inputs:
  github-token:
    description: 'Personal access token with repository rights.'
    required: true
  mattermost-webhook:
    description: 'Mattermost Webhook URL.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
