name: Test Run
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: pr-reviewer-notify-cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-${{ env.cache-name }}-
            ${{ runner.OS }}-
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
      - name: Install Packages
        run: yarn
      - name: Build
        run: yarn build
      - name: run pr reviewer notify action
        uses: ./
        id: pr-reviewer-notify
        # run: npx ts-node index.ts
        with:
          slack-channel-id: ${{ secrets.TEST_SLACK_CHANNEL_ID }}
          base-branch: main
          github-token: ${{ secrets.TEST_GITHUB_TOKEN }}
